package com.techtorque.admin_service.repository;

import com.techtorque.admin_service.entity.Report;
import com.techtorque.admin_service.entity.ReportStatus;
import com.techtorque.admin_service.entity.ReportType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Repository for Report entity
 * File Location: src/main/java/com/techtorque/admin_service/repository/ReportRepository.java
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, String> {

    /**
     * Find reports by type
     */
    List<Report> findByType(ReportType type);

    /**
     * Find reports by type with pagination
     */
    Page<Report> findByType(ReportType type, Pageable pageable);

    /**
     * Find reports generated by specific user
     */
    List<Report> findByGeneratedBy(String userId);

    /**
     * Find reports generated by user with pagination
     */
    Page<Report> findByGeneratedBy(String userId, Pageable pageable);

    /**
     * Find reports by status
     */
    List<Report> findByStatus(ReportStatus status);

    /**
     * Find scheduled reports
     */
    List<Report> findByIsScheduledTrue();

    /**
     * Find reports created within date range
     */
    @Query("SELECT r FROM Report r WHERE r.createdAt BETWEEN :startDate AND :endDate ORDER BY r.createdAt DESC")
    List<Report> findByDateRange(@Param("startDate") LocalDateTime startDate,
                                 @Param("endDate") LocalDateTime endDate);

    /**
     * Find reports with pagination and sorting
     */
    @Query("SELECT r FROM Report r WHERE r.createdAt BETWEEN :startDate AND :endDate ORDER BY r.createdAt DESC")
    Page<Report> findByDateRange(@Param("startDate") LocalDateTime startDate,
                                 @Param("endDate") LocalDateTime endDate,
                                 Pageable pageable);

    /**
     * Find reports by type and status
     */
    List<Report> findByTypeAndStatus(ReportType type, ReportStatus status);

    /**
     * Count reports by type
     */
    Long countByType(ReportType type);

    /**
     * Count reports by status
     */
    Long countByStatus(ReportStatus status);

    /**
     * Find completed reports in the last N days
     */
    @Query("SELECT r FROM Report r WHERE r.status = 'COMPLETED' AND r.completedAt >= :sinceDate ORDER BY r.completedAt DESC")
    List<Report> findRecentCompletedReports(@Param("sinceDate") LocalDateTime sinceDate);
}
