package com.techtorque.admin_service.util;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.techtorque.admin_service.dto.external.AppointmentDto;
import com.techtorque.admin_service.dto.external.InvoiceDto;
import com.techtorque.admin_service.entity.Report;
import com.techtorque.admin_service.entity.ReportType;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;

@Component
@RequiredArgsConstructor
@Slf4j
public class PdfReportGenerator {

    private final ObjectMapper objectMapper;

    public byte[] generatePdf(Report report) throws IOException {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, out);

            document.open();

            // Add Title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
            Paragraph title = new Paragraph(report.getTitle(), titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            // Add Metadata
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.GRAY);
            document.add(new Paragraph("Generated By: " + report.getGeneratedBy(), metaFont));
            document.add(new Paragraph("Date Range: " + report.getFromDate() + " to " + report.getToDate(), metaFont));
            document.add(new Paragraph("Generated At: " + report.getCreatedAt(), metaFont));
            document.add(new Paragraph("\n"));

            // Add Content based on type
            if (report.getType() == ReportType.APPOINTMENT_SUMMARY) {
                generateAppointmentSummaryContent(document, report.getDataJson());
            } else if (report.getType() == ReportType.REVENUE) {
                generateRevenueReportContent(document, report.getDataJson());
            } else {
                document.add(new Paragraph("PDF generation not implemented for this report type."));
            }

            document.close();
            return out.toByteArray();
        }
    }

    private void generateAppointmentSummaryContent(Document document, String json) throws IOException {
        Map<String, Object> data = objectMapper.readValue(json, new TypeReference<>() {
        });

        // Summary Section
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.BLACK);
        document.add(new Paragraph("Summary", headerFont));
        document.add(new Paragraph("Total Appointments: " + data.get("totalAppointments")));
        document.add(new Paragraph("\n"));

        // Status Breakdown
        document.add(new Paragraph("Status Breakdown", headerFont));
        Map<String, Integer> statusBreakdown = objectMapper.convertValue(data.get("statusBreakdown"),
                new TypeReference<>() {
                });
        PdfPTable statusTable = new PdfPTable(2);
        statusTable.setWidthPercentage(100);
        statusTable.addCell("Status");
        statusTable.addCell("Count");
        statusBreakdown.forEach((k, v) -> {
            statusTable.addCell(k);
            statusTable.addCell(String.valueOf(v));
        });
        document.add(statusTable);
        document.add(new Paragraph("\n"));

        // Appointments List
        document.add(new Paragraph("Appointment Details", headerFont));
        List<AppointmentDto> appointments = objectMapper.convertValue(data.get("appointments"), new TypeReference<>() {
        });

        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[] { 2, 2, 2, 2, 2 });

        addTableHeader(table, "ID", "Customer", "Service", "Date", "Status");

        for (AppointmentDto appt : appointments) {
            table.addCell(appt.getId().substring(0, 8));
            table.addCell(appt.getCustomerId()); // Ideally fetch customer name
            table.addCell(appt.getServiceType());
            table.addCell(appt.getRequestedDateTime().toString());
            table.addCell(appt.getStatus());
        }
        document.add(table);
    }

    private void generateRevenueReportContent(Document document, String json) throws IOException {
        Map<String, Object> data = objectMapper.readValue(json, new TypeReference<>() {
        });

        // Summary Section
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.BLACK);
        document.add(new Paragraph("Financial Summary", headerFont));
        document.add(new Paragraph("Total Revenue: " + data.get("totalRevenue")));
        document.add(new Paragraph("Total Paid: " + data.get("totalPaid")));
        document.add(new Paragraph("Outstanding: " + data.get("outstandingAmount")));
        document.add(new Paragraph("\n"));

        // Invoices List
        document.add(new Paragraph("Invoice Details", headerFont));
        List<InvoiceDto> invoices = objectMapper.convertValue(data.get("invoices"), new TypeReference<>() {
        });

        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[] { 2, 2, 2, 2, 2 });

        addTableHeader(table, "Invoice ID", "Customer", "Amount", "Status", "Date");

        for (InvoiceDto inv : invoices) {
            table.addCell(inv.getInvoiceId().substring(0, 8));
            table.addCell(inv.getCustomerId());
            table.addCell(String.valueOf(inv.getTotalAmount()));
            table.addCell(inv.getStatus());
            table.addCell(inv.getIssuedAt().toString());
        }
        document.add(table);
    }

    private void addTableHeader(PdfPTable table, String... headers) {
        for (String header : headers) {
            PdfPCell headerCell = new PdfPCell();
            headerCell.setBackgroundColor(Color.LIGHT_GRAY);
            headerCell.setPhrase(new Phrase(header, FontFactory.getFont(FontFactory.HELVETICA_BOLD)));
            table.addCell(headerCell);
        }
    }
}
